-- =========================================================
-- AquaNexus — SQL Data Initialization
-- Database starts clean. User inputs records via UI form.
-- =========================================================
